services:
  backend:
    build: ./api
    ports:
      - "8080:8080"
    networks:
    - redway

  web-app:
    build: ./webapp
    environment:
      - NEXT_PUBLIC_URL=http://backend:8080
    ports: 
      - "3000:3000"
    networks:
      - redway
    depends_on:
     - backend

networks:
  redway:
    external: true